<<<<<<< HEAD

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: content_store_development
  pool: 5
  username: root
  password: root

=======
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: content_store_development
  pool: 5
  username: root
  password: root

>>>>>>> d96609ac841b94e301ffaddaec12ab35c74ae0fb
# 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: content_store_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: content_store_production
  pool: 5
  username: root
  password: root