
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: CS_database
  pool: 5
  username: root
  password: root

# 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: CS_database_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: content_store_production
  pool: 5
  username: root
  password: root